# SPDX-License-Identifier: LGPL-2.1-or-later

"""Explicit provider function-tool module registry for VibeCAD."""

from __future__ import annotations

from importlib import import_module


TOOL_MODULES = {
    "core.get_current_freecad_context": "provider_tools.core_get_current_freecad_context",
    "core.get_active_document": "provider_tools.core_get_active_document",
    "core.get_selection": "provider_tools.core_get_selection",
    "core.get_view_state": "provider_tools.core_get_view_state",
    "core.get_task_panel": "provider_tools.core_get_task_panel",
    "core.wait_for_user_gui_action": "provider_tools.core_wait_for_user_gui_action",
    "core.capture_view_screenshot": "provider_tools.core_capture_view_screenshot",
    "core.get_report_view_errors": "provider_tools.core_get_report_view_errors",
    "core.list_workbenches": "provider_tools.core_list_workbenches",
    "core.list_registered_commands": "provider_tools.core_list_registered_commands",
    "core.list_active_workbench_commands": "provider_tools.core_list_active_workbench_commands",
    "core.get_tool_shape_report": "provider_tools.core_get_tool_shape_report",
    "core.report_tool_shape_gap": "provider_tools.core_report_tool_shape_gap",
    "core.activate_workbench": "provider_tools.core_activate_workbench",
    "core.get_active_workbench_tool_pack": "provider_tools.core_get_active_workbench_tool_pack",
    "core.list_workbench_tool_packs": "provider_tools.core_list_workbench_tool_packs",
    "core.list_workbench_object_templates": "provider_tools.core_list_workbench_object_templates",
    "core.list_workbench_objects": "provider_tools.core_list_workbench_objects",
    "core.get_object_properties": "provider_tools.core_get_object_properties",
    "part.get_objects": "provider_tools.part_get_objects",
    "part.create_primitive": "provider_tools.part_create_primitive",
    "part.set_placement": "provider_tools.part_set_placement",
    "part.set_primitive_dimensions": "provider_tools.part_set_primitive_dimensions",
    "part.cut_cylindrical_hole": "provider_tools.part_cut_cylindrical_hole",
    "part.apply_fillet": "provider_tools.part_apply_fillet",
    "part.apply_chamfer": "provider_tools.part_apply_chamfer",
    "part.apply_thickness": "provider_tools.part_apply_thickness",
    "draft.create_array": "provider_tools.draft_create_array",
    "mesh.get_objects": "provider_tools.mesh_get_objects",
    "points.get_objects": "provider_tools.points_get_objects",
    "material.get_objects": "provider_tools.material_get_objects",
    "material.apply_appearance": "provider_tools.material_apply_appearance",
    "core.create_new_document": "provider_tools.core_create_new_document",
    "core.open_document": "provider_tools.core_open_document",
    "core.delete_object": "provider_tools.core_delete_object",
    "partdesign.create_body": "provider_tools.partdesign_create_body",
    "partdesign.create_sketch": "provider_tools.partdesign_create_sketch",
    "partdesign.create_datum_plane": "provider_tools.partdesign_create_datum_plane",
    "partdesign.create_datum_line": "provider_tools.partdesign_create_datum_line",
    "partdesign.pad_sketch": "provider_tools.partdesign_pad_sketch",
    "partdesign.pocket_sketch": "provider_tools.partdesign_pocket_sketch",
    "partdesign.hole_from_sketch": "provider_tools.partdesign_hole_from_sketch",
    "partdesign.revolve_sketch": "provider_tools.partdesign_revolve_sketch",
    "partdesign.groove_sketch": "provider_tools.partdesign_groove_sketch",
    "partdesign.fillet_feature": "provider_tools.partdesign_fillet_feature",
    "partdesign.loft_profiles": "provider_tools.partdesign_loft_profiles",
    "partdesign.sweep_profile": "provider_tools.partdesign_sweep_profile",
    "partdesign.helix_profile": "provider_tools.partdesign_helix_profile",
    "partdesign.linear_pattern": "provider_tools.partdesign_linear_pattern",
    "partdesign.polar_pattern": "provider_tools.partdesign_polar_pattern",
    "partdesign.mirror_feature": "provider_tools.partdesign_mirror_feature",
    "partdesign.chamfer_feature": "provider_tools.partdesign_chamfer_feature",
    "partdesign.thickness_feature": "provider_tools.partdesign_thickness_feature",
    "partdesign.draft_feature": "provider_tools.partdesign_draft_feature",
    "partdesign.boolean_bodies": "provider_tools.partdesign_boolean_bodies",
    "partdesign.set_feature_dimensions": "provider_tools.partdesign_set_feature_dimensions",
    "sketcher.get_sketch": "provider_tools.sketcher_get_sketch",
    "sketcher.create_sketch": "provider_tools.sketcher_create_sketch",
    "sketcher.open_sketch": "provider_tools.sketcher_open_sketch",
    "sketcher.close_sketch": "provider_tools.sketcher_close_sketch",
    "sketcher.get_solver_status": "provider_tools.sketcher_get_solver_status",
    "sketcher.validate_profile": "provider_tools.sketcher_validate_profile",
    "sketcher.validate_profile_deep": "provider_tools.sketcher_validate_profile_deep",
    "sketcher.diagnose_constraints": "provider_tools.sketcher_diagnose_constraints",
    "sketcher.list_geometry": "provider_tools.sketcher_list_geometry",
    "sketcher.list_constraints": "provider_tools.sketcher_list_constraints",
    "sketcher.resolve_geometry": "provider_tools.sketcher_resolve_geometry",
    "sketcher.set_geometry_name": "provider_tools.sketcher_set_geometry_name",
    "sketcher.list_reference_geometry": "provider_tools.sketcher_list_reference_geometry",
    "sketcher.list_external_geometry": "provider_tools.sketcher_list_external_geometry",
    "sketcher.draw_rectangle": "provider_tools.sketcher_draw_rectangle",
    "sketcher.add_line": "provider_tools.sketcher_add_line",
    "sketcher.add_point": "provider_tools.sketcher_add_point",
    "sketcher.add_polyline": "provider_tools.sketcher_add_polyline",
    "sketcher.add_circle": "provider_tools.sketcher_add_circle",
    "sketcher.add_arc": "provider_tools.sketcher_add_arc",
    "sketcher.add_ellipse": "provider_tools.sketcher_add_ellipse",
    "sketcher.add_bspline": "provider_tools.sketcher_add_bspline",
    "sketcher.add_slot": "provider_tools.sketcher_add_slot",
    "sketcher.add_constraint": "provider_tools.sketcher_add_constraint",
    "sketcher.constrain_coincident": "provider_tools.sketcher_constrain_coincident",
    "sketcher.constrain_horizontal": "provider_tools.sketcher_constrain_horizontal",
    "sketcher.constrain_vertical": "provider_tools.sketcher_constrain_vertical",
    "sketcher.constrain_parallel": "provider_tools.sketcher_constrain_parallel",
    "sketcher.constrain_perpendicular": "provider_tools.sketcher_constrain_perpendicular",
    "sketcher.constrain_tangent": "provider_tools.sketcher_constrain_tangent",
    "sketcher.constrain_equal": "provider_tools.sketcher_constrain_equal",
    "sketcher.constrain_distance": "provider_tools.sketcher_constrain_distance",
    "sketcher.constrain_distance_points": "provider_tools.sketcher_constrain_distance_points",
    "sketcher.constrain_distance_x": "provider_tools.sketcher_constrain_distance_x",
    "sketcher.constrain_distance_y": "provider_tools.sketcher_constrain_distance_y",
    "sketcher.constrain_angle_between": "provider_tools.sketcher_constrain_angle_between",
    "sketcher.constrain_lock_point": "provider_tools.sketcher_constrain_lock_point",
    "sketcher.constrain_block_geometry": "provider_tools.sketcher_constrain_block_geometry",
    "sketcher.constrain_radius": "provider_tools.sketcher_constrain_radius",
    "sketcher.constrain_diameter": "provider_tools.sketcher_constrain_diameter",
    "sketcher.constrain_point_on_object": "provider_tools.sketcher_constrain_point_on_object",
    "sketcher.constrain_point_on_reference": "provider_tools.sketcher_constrain_point_on_reference",
    "sketcher.constrain_symmetric": "provider_tools.sketcher_constrain_symmetric",
    "sketcher.get_constraint_by_name": "provider_tools.sketcher_get_constraint_by_name",
    "sketcher.set_constraint_name": "provider_tools.sketcher_set_constraint_name",
    "sketcher.set_constraint_value": "provider_tools.sketcher_set_constraint_value",
    "sketcher.set_constraint_value_by_name": "provider_tools.sketcher_set_constraint_value_by_name",
    "sketcher.set_constraint_driving": "provider_tools.sketcher_set_constraint_driving",
    "sketcher.set_constraint_expression": "provider_tools.sketcher_set_constraint_expression",
    "sketcher.move_point": "provider_tools.sketcher_move_point",
    "sketcher.transform_geometry": "provider_tools.sketcher_transform_geometry",
    "sketcher.copy_geometry": "provider_tools.sketcher_copy_geometry",
    "sketcher.rectangular_array": "provider_tools.sketcher_rectangular_array",
    "sketcher.mirror_geometry": "provider_tools.sketcher_mirror_geometry",
    "sketcher.offset_geometry": "provider_tools.sketcher_offset_geometry",
    "sketcher.trim_geometry": "provider_tools.sketcher_trim_geometry",
    "sketcher.extend_geometry": "provider_tools.sketcher_extend_geometry",
    "sketcher.split_geometry": "provider_tools.sketcher_split_geometry",
    "sketcher.fillet_corner": "provider_tools.sketcher_fillet_corner",
    "sketcher.add_external_geometry": "provider_tools.sketcher_add_external_geometry",
    "sketcher.remove_external_geometry": "provider_tools.sketcher_remove_external_geometry",
    "sketcher.delete_geometry": "provider_tools.sketcher_delete_geometry",
    "sketcher.delete_constraint": "provider_tools.sketcher_delete_constraint",
    "sketcher.delete_all_geometry": "provider_tools.sketcher_delete_all_geometry",
    "sketcher.delete_all_constraints": "provider_tools.sketcher_delete_all_constraints",
    "sketcher.set_construction": "provider_tools.sketcher_set_construction",
    "spreadsheet.get_sheet": "provider_tools.spreadsheet_get_sheet",
    "draft.get_objects": "provider_tools.draft_get_objects",
    "partdesign.get_bodies": "provider_tools.partdesign_get_bodies",
    "techdraw.get_pages": "provider_tools.techdraw_get_pages",
    "techdraw.create_page": "provider_tools.techdraw_create_page",
    "techdraw.add_view": "provider_tools.techdraw_add_view",
    "fem.get_analyses": "provider_tools.fem_get_analyses",
    "cam.get_jobs": "provider_tools.cam_get_jobs",
    "bim.get_objects": "provider_tools.bim_get_objects",
    "assembly.get_assemblies": "provider_tools.assembly_get_assemblies",
    "assembly.create_assembly": "provider_tools.assembly_create_assembly",
    "assembly.add_component": "provider_tools.assembly_add_component",
    "assembly.set_component_placement": "provider_tools.assembly_set_component_placement",
    "inspection.get_objects": "provider_tools.inspection_get_objects",
    "openscad.get_objects": "provider_tools.openscad_get_objects",
    "surface.get_objects": "provider_tools.surface_get_objects",
    "reverseengineering.get_objects": "provider_tools.reverseengineering_get_objects",
    "robot.get_objects": "provider_tools.robot_get_objects",
    "meshpart.get_objects": "provider_tools.meshpart_get_objects",
}


def create_tool(schema, conn, FunctionTool):
    tool_name = str(schema.get("name", ""))
    module_name = TOOL_MODULES.get(tool_name)
    if module_name is None:
        raise KeyError(f"No provider tool module is registered for {tool_name}")
    module = import_module(module_name)
    return module.create(schema, conn, FunctionTool)


def create_context_tool(schema, context, FunctionTool):
    tool_name = str(schema.get("name", ""))
    module_name = TOOL_MODULES.get(tool_name)
    if module_name is None:
        raise KeyError(f"No provider tool module is registered for {tool_name}")
    module = import_module(module_name)
    return module.create(schema, context, FunctionTool)


def registered_tool_names():
    return set(TOOL_MODULES)
